-- Volt baseline schema (V1).
-- Authoritative source: generated by Hibernate for the PostgreSQL dialect from the
-- JPA entity model, then hand-finalized (stable FK/constraint names, readable column
-- order). Column names and types are kept verbatim so `spring.jpa.hibernate.ddl-auto=validate`
-- passes against this schema. Schema-change rule lives in backend/CLAUDE.md ("Schema changes"):
-- this V1 baseline is edited in place until the first real users exist, and the local stack must
-- be wiped after any edit; once deployed, add V2, V3, ... instead.

-- ── users ───────────────────────────────────────────────────────────────────
create table users (
    id                   uuid not null,
    username             varchar(30) not null unique,
    email                varchar(255) not null unique,
    password_hash        varchar(255),
    google_sub           varchar(255) unique,
    display_name         varchar(50),
    bio                  varchar(300),
    profile_picture_url  varchar(255),
    date_of_birth        date,
    gender               varchar(20) check (gender in ('MALE','FEMALE','OTHER','PREFER_NOT_TO_SAY')),
    height_cm            integer,
    weight_kg            float(53),
    created_at           timestamp(6) with time zone not null,
    updated_at           timestamp(6) with time zone not null,
    deleted_at           timestamp(6) with time zone,
    primary key (id)
);

-- ── refresh_tokens (not a BaseEntity — no audit columns) ─────────────────────
create table refresh_tokens (
    id          uuid not null,
    user_id     uuid not null,
    token       varchar(255) not null unique,
    expires_at  timestamp(6) with time zone not null,
    revoked     boolean not null,
    primary key (id)
);

-- ── exercises ────────────────────────────────────────────────────────────────
create table exercises (
    id                   uuid not null,
    created_by_user_id   uuid,
    name                 varchar(100) not null,
    description          varchar(500),
    primary_muscle_group varchar(20) not null check (primary_muscle_group in ('CHEST','BACK','SHOULDERS','BICEPS','TRICEPS','QUADRICEPS','HAMSTRINGS','GLUTES','CALVES','CORE','FOREARMS','FULL_BODY')),
    equipment            varchar(20) not null check (equipment in ('BARBELL','DUMBBELL','MACHINE','CABLE','BODYWEIGHT','KETTLEBELL','RESISTANCE_BAND','OTHER')),
    movement_type        varchar(20) not null check (movement_type in ('COMPOUND','ISOLATION')),
    measurement_type     varchar(20) not null check (measurement_type in ('REPS_WEIGHT','DISTANCE','DURATION','REPS_ONLY')),
    system               boolean not null,
    created_at           timestamp(6) with time zone not null,
    updated_at           timestamp(6) with time zone not null,
    deleted_at           timestamp(6) with time zone,
    primary key (id)
);

-- ── exercise_secondary_muscles (@ElementCollection) ──────────────────────────
create table exercise_secondary_muscles (
    exercise_id  uuid not null,
    muscle_group varchar(20) check (muscle_group in ('CHEST','BACK','SHOULDERS','BICEPS','TRICEPS','QUADRICEPS','HAMSTRINGS','GLUTES','CALVES','CORE','FOREARMS','FULL_BODY'))
);

-- ── routines ─────────────────────────────────────────────────────────────────
create table routines (
    id          uuid not null,
    user_id     uuid not null,
    name        varchar(100) not null,
    notes       varchar(1000),
    created_at  timestamp(6) with time zone not null,
    updated_at  timestamp(6) with time zone not null,
    deleted_at  timestamp(6) with time zone,
    primary key (id)
);

create table routine_exercises (
    id           uuid not null,
    routine_id   uuid not null,
    exercise_id  uuid not null,
    position     integer not null,
    target_sets  integer,
    target_reps  integer,
    rest_seconds integer,
    notes        varchar(300),
    created_at   timestamp(6) with time zone not null,
    updated_at   timestamp(6) with time zone not null,
    deleted_at   timestamp(6) with time zone,
    primary key (id)
);

-- ── workouts ─────────────────────────────────────────────────────────────────
create table workouts (
    id           uuid not null,
    user_id      uuid not null,
    title        varchar(100),
    notes        varchar(1000),
    started_at   timestamp(6) with time zone not null,
    completed_at timestamp(6) with time zone,
    rpe          integer check ((rpe>=1) and (rpe<=10)),
    created_at   timestamp(6) with time zone not null,
    updated_at   timestamp(6) with time zone not null,
    deleted_at   timestamp(6) with time zone,
    primary key (id)
);

create table workout_exercises (
    id           uuid not null,
    workout_id   uuid not null,
    exercise_id  uuid not null,
    position     integer not null,
    rest_seconds integer,
    notes        varchar(300),
    created_at   timestamp(6) with time zone not null,
    updated_at   timestamp(6) with time zone not null,
    deleted_at   timestamp(6) with time zone,
    primary key (id)
);

create table workout_sets (
    id                  uuid not null,
    workout_exercise_id uuid not null,
    set_number          integer not null,
    set_type            varchar(20) not null check (set_type in ('NORMAL','WARMUP','DROP_SET','FAILURE')),
    reps                integer check (reps>=0),
    weight_kg           float(53),
    duration_seconds    integer,
    distance_meters     float(53),
    rpe                 integer check ((rpe>=1) and (rpe<=10)),
    notes               varchar(300),
    completed_at        timestamp(6) with time zone,
    is_pr               boolean not null,
    created_at          timestamp(6) with time zone not null,
    updated_at          timestamp(6) with time zone not null,
    deleted_at          timestamp(6) with time zone,
    primary key (id)
);

-- ── personal_records ─────────────────────────────────────────────────────────
create table personal_records (
    id             uuid not null,
    user_id        uuid not null,
    exercise_id    uuid not null,
    workout_set_id uuid,
    type           varchar(20) not null check (type in ('ONE_REP_MAX','MAX_WEIGHT','MAX_VOLUME','MAX_REPS_AT_WEIGHT')),
    record_value   float(53) not null,
    achieved_at    timestamp(6) with time zone not null,
    created_at     timestamp(6) with time zone not null,
    updated_at     timestamp(6) with time zone not null,
    deleted_at     timestamp(6) with time zone,
    primary key (id),
    constraint uq_pr_user_exercise_type unique (user_id, exercise_id, type)
);

-- ── activities ───────────────────────────────────────────────────────────────
create table activities (
    id                    uuid not null,
    user_id               uuid not null,
    title                 varchar(100),
    type                  varchar(20) not null check (type in ('RUN','RIDE','HIKE','WALK','SWIM','ROW','OTHER')),
    started_at            timestamp(6) with time zone not null,
    completed_at          timestamp(6) with time zone,
    duration_seconds      integer check (duration_seconds>=0),
    distance_meters       float(53) check (distance_meters>=0),
    elevation_gain_meters float(53),
    average_heart_rate    integer,
    max_heart_rate        integer,
    calories              integer,
    notes                 varchar(1000),
    created_at            timestamp(6) with time zone not null,
    updated_at            timestamp(6) with time zone not null,
    deleted_at            timestamp(6) with time zone,
    primary key (id)
);

create table routes (
    id               uuid not null,
    activity_id      uuid not null unique,
    encoded_polyline text,
    elevation_data   text,
    created_at       timestamp(6) with time zone not null,
    updated_at       timestamp(6) with time zone not null,
    deleted_at       timestamp(6) with time zone,
    primary key (id)
);

create table laps (
    id                      uuid not null,
    activity_id             uuid not null,
    lap_number              integer not null,
    distance_meters         float(53),
    duration_seconds        integer,
    average_pace_min_per_km float(53),
    average_heart_rate      integer,
    created_at              timestamp(6) with time zone not null,
    updated_at              timestamp(6) with time zone not null,
    deleted_at              timestamp(6) with time zone,
    primary key (id)
);

-- ── indexes ──────────────────────────────────────────────────────────────────
create index idx_users_username on users (username);
create index idx_users_email on users (email);
create index idx_refresh_tokens_token on refresh_tokens (token);
create index idx_refresh_tokens_user_id on refresh_tokens (user_id);
create index idx_exercises_created_by on exercises (created_by_user_id);
create index idx_routines_user_id on routines (user_id);
create index idx_routine_exercises_routine_id on routine_exercises (routine_id);
create index idx_routine_exercises_exercise_id on routine_exercises (exercise_id);
create index idx_workouts_user_id on workouts (user_id);
create index idx_workouts_started_at on workouts (started_at);
create index idx_workout_exercises_workout_id on workout_exercises (workout_id);
create index idx_workout_exercises_exercise_id on workout_exercises (exercise_id);
create index idx_workout_sets_workout_exercise_id on workout_sets (workout_exercise_id);
create index idx_pr_user_exercise on personal_records (user_id, exercise_id);
create index idx_activities_user_id on activities (user_id);
create index idx_activities_started_at on activities (started_at);
create index idx_laps_activity_id on laps (activity_id);

-- ── foreign keys ─────────────────────────────────────────────────────────────
alter table refresh_tokens          add constraint fk_refresh_tokens_user             foreign key (user_id)             references users (id);
alter table exercises               add constraint fk_exercises_created_by            foreign key (created_by_user_id)  references users (id);
alter table exercise_secondary_muscles add constraint fk_exercise_secondary_muscles_exercise foreign key (exercise_id) references exercises (id);
alter table routines                add constraint fk_routines_user                   foreign key (user_id)             references users (id);
alter table routine_exercises       add constraint fk_routine_exercises_routine       foreign key (routine_id)          references routines (id);
alter table routine_exercises       add constraint fk_routine_exercises_exercise      foreign key (exercise_id)         references exercises (id);
alter table workouts                add constraint fk_workouts_user                   foreign key (user_id)             references users (id);
alter table workout_exercises       add constraint fk_workout_exercises_workout       foreign key (workout_id)          references workouts (id);
alter table workout_exercises       add constraint fk_workout_exercises_exercise      foreign key (exercise_id)         references exercises (id);
alter table workout_sets            add constraint fk_workout_sets_workout_exercise   foreign key (workout_exercise_id) references workout_exercises (id);
alter table personal_records        add constraint fk_personal_records_user           foreign key (user_id)             references users (id);
alter table personal_records        add constraint fk_personal_records_exercise       foreign key (exercise_id)         references exercises (id);
alter table personal_records        add constraint fk_personal_records_workout_set    foreign key (workout_set_id)      references workout_sets (id);
alter table activities              add constraint fk_activities_user                 foreign key (user_id)             references users (id);
alter table routes                  add constraint fk_routes_activity                 foreign key (activity_id)         references activities (id);
alter table laps                    add constraint fk_laps_activity                   foreign key (activity_id)         references activities (id);
