/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/routines/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getById"];
        put: operations["update"];
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getById_1"];
        put: operations["update_1"];
        post?: never;
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workouts/{id}/sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addSet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["uploadAvatar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routines/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_2"];
        put?: never;
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["google"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_3"];
        put?: never;
        post: operations["create_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workouts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getById_2"];
        put?: never;
        post?: never;
        delete: operations["delete_2"];
        options?: never;
        head?: never;
        patch: operations["update_2"];
        trace?: never;
    };
    "/api/workouts/{id}/sets/{setId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["removeSet"];
        options?: never;
        head?: never;
        patch: operations["updateSet"];
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSelf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateProfile"];
        trace?: never;
    };
    "/api/activities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getById_3"];
        put?: never;
        post?: never;
        delete: operations["delete_3"];
        options?: never;
        head?: never;
        patch: operations["update_3"];
        trace?: never;
    };
    "/api/workouts/last-sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["lastSets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRecords"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/{id}/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["records"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/{id}/progression": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["progression"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exercises/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateRoutineExerciseRequest: {
            /** Format: uuid */
            exerciseId: string;
            /** Format: int32 */
            targetSets?: number;
            /** Format: int32 */
            targetReps?: number;
            /** Format: int32 */
            restSeconds?: number;
            notes?: string;
        };
        CreateRoutineRequest: {
            name: string;
            notes?: string;
            exercises?: components["schemas"]["CreateRoutineExerciseRequest"][];
        };
        RoutineExerciseResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            exerciseId?: string;
            exerciseName?: string;
            /** Format: int32 */
            position?: number;
            /** Format: int32 */
            targetSets?: number;
            /** Format: int32 */
            targetReps?: number;
            /** Format: int32 */
            restSeconds?: number;
            notes?: string;
        };
        RoutineResponse: {
            /** Format: uuid */
            id?: string;
            name?: string;
            notes?: string;
            exercises?: components["schemas"]["RoutineExerciseResponse"][];
            /** Format: date-time */
            createdAt?: string;
        };
        UpdateExerciseRequest: {
            name?: string;
            description?: string;
            /** @enum {string} */
            primaryMuscleGroup?: "CHEST" | "BACK" | "SHOULDERS" | "BICEPS" | "TRICEPS" | "QUADRICEPS" | "HAMSTRINGS" | "GLUTES" | "CALVES" | "CORE" | "FOREARMS" | "FULL_BODY";
            secondaryMuscleGroups?: ("CHEST" | "BACK" | "SHOULDERS" | "BICEPS" | "TRICEPS" | "QUADRICEPS" | "HAMSTRINGS" | "GLUTES" | "CALVES" | "CORE" | "FOREARMS" | "FULL_BODY")[];
            /** @enum {string} */
            equipment?: "BARBELL" | "DUMBBELL" | "MACHINE" | "CABLE" | "BODYWEIGHT" | "KETTLEBELL" | "RESISTANCE_BAND" | "OTHER";
            /** @enum {string} */
            movementType?: "COMPOUND" | "ISOLATION";
            /** @enum {string} */
            measurementType?: "REPS_WEIGHT" | "DISTANCE" | "DURATION" | "REPS_ONLY";
        };
        ExerciseResponse: {
            /** Format: uuid */
            id?: string;
            name?: string;
            description?: string;
            /** @enum {string} */
            primaryMuscleGroup?: "CHEST" | "BACK" | "SHOULDERS" | "BICEPS" | "TRICEPS" | "QUADRICEPS" | "HAMSTRINGS" | "GLUTES" | "CALVES" | "CORE" | "FOREARMS" | "FULL_BODY";
            secondaryMuscleGroups?: ("CHEST" | "BACK" | "SHOULDERS" | "BICEPS" | "TRICEPS" | "QUADRICEPS" | "HAMSTRINGS" | "GLUTES" | "CALVES" | "CORE" | "FOREARMS" | "FULL_BODY")[];
            /** @enum {string} */
            equipment?: "BARBELL" | "DUMBBELL" | "MACHINE" | "CABLE" | "BODYWEIGHT" | "KETTLEBELL" | "RESISTANCE_BAND" | "OTHER";
            /** @enum {string} */
            movementType?: "COMPOUND" | "ISOLATION";
            /** @enum {string} */
            measurementType?: "REPS_WEIGHT" | "DISTANCE" | "DURATION" | "REPS_ONLY";
            system?: boolean;
        };
        CreateWorkoutExerciseRequest: {
            /** Format: uuid */
            exerciseId: string;
            notes?: string;
            /** Format: int32 */
            restSeconds?: number;
            sets: components["schemas"]["CreateWorkoutSetRequest"][];
        };
        CreateWorkoutRequest: {
            title?: string;
            notes?: string;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            completedAt?: string;
            /** Format: int32 */
            rpe?: number;
            exercises?: components["schemas"]["CreateWorkoutExerciseRequest"][];
        };
        CreateWorkoutSetRequest: {
            /** @enum {string} */
            setType?: "NORMAL" | "WARMUP" | "DROP_SET" | "FAILURE";
            /** Format: int32 */
            reps?: number;
            /** Format: double */
            weightKg?: number;
            /** Format: int32 */
            durationSeconds?: number;
            /** Format: double */
            distanceMeters?: number;
            /** Format: int32 */
            rpe?: number;
            notes?: string;
            /** Format: date-time */
            completedAt?: string;
        };
        WorkoutExerciseResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            exerciseId?: string;
            exerciseName?: string;
            /** Format: int32 */
            position?: number;
            notes?: string;
            /** Format: int32 */
            restSeconds?: number;
            sets?: components["schemas"]["WorkoutSetResponse"][];
        };
        WorkoutResponse: {
            /** Format: uuid */
            id?: string;
            title?: string;
            notes?: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            completedAt?: string;
            /** Format: int32 */
            rpe?: number;
            inProgress?: boolean;
            /** Format: double */
            totalVolumeKg?: number;
            exercises?: components["schemas"]["WorkoutExerciseResponse"][];
            /** Format: date-time */
            createdAt?: string;
        };
        WorkoutSetResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            exerciseId?: string;
            exerciseName?: string;
            /** Format: int32 */
            setNumber?: number;
            /** @enum {string} */
            setType?: "NORMAL" | "WARMUP" | "DROP_SET" | "FAILURE";
            /** Format: int32 */
            reps?: number;
            /** Format: double */
            weightKg?: number;
            /** Format: int32 */
            durationSeconds?: number;
            /** Format: double */
            distanceMeters?: number;
            /** Format: int32 */
            rpe?: number;
            notes?: string;
            /** Format: date-time */
            completedAt?: string;
            isPr?: boolean;
        };
        AddSetRequest: {
            /** Format: uuid */
            exerciseId: string;
            /** @enum {string} */
            setType?: "NORMAL" | "WARMUP" | "DROP_SET" | "FAILURE";
            /** Format: int32 */
            reps?: number;
            /** Format: double */
            weightKg?: number;
            /** Format: int32 */
            durationSeconds?: number;
            /** Format: double */
            distanceMeters?: number;
            /** Format: int32 */
            rpe?: number;
            notes?: string;
        };
        UserSelfResponse: {
            /** Format: uuid */
            id?: string;
            username?: string;
            email?: string;
            displayName?: string;
            bio?: string;
            profilePictureUrl?: string;
            /** Format: date */
            dateOfBirth?: string;
            /** @enum {string} */
            gender?: "MALE" | "FEMALE" | "OTHER" | "PREFER_NOT_TO_SAY";
            /** Format: int32 */
            heightCm?: number;
            /** Format: double */
            weightKg?: number;
            /** Format: date-time */
            joinedAt?: string;
        };
        CreateExerciseRequest: {
            name: string;
            description?: string;
            /** @enum {string} */
            primaryMuscleGroup: "CHEST" | "BACK" | "SHOULDERS" | "BICEPS" | "TRICEPS" | "QUADRICEPS" | "HAMSTRINGS" | "GLUTES" | "CALVES" | "CORE" | "FOREARMS" | "FULL_BODY";
            secondaryMuscleGroups?: ("CHEST" | "BACK" | "SHOULDERS" | "BICEPS" | "TRICEPS" | "QUADRICEPS" | "HAMSTRINGS" | "GLUTES" | "CALVES" | "CORE" | "FOREARMS" | "FULL_BODY")[];
            /** @enum {string} */
            equipment: "BARBELL" | "DUMBBELL" | "MACHINE" | "CABLE" | "BODYWEIGHT" | "KETTLEBELL" | "RESISTANCE_BAND" | "OTHER";
            /** @enum {string} */
            movementType: "COMPOUND" | "ISOLATION";
            /** @enum {string} */
            measurementType?: "REPS_WEIGHT" | "DISTANCE" | "DURATION" | "REPS_ONLY";
        };
        RegisterRequest: {
            username: string;
            email: string;
            password: string;
        };
        AuthResponse: {
            accessToken?: string;
            refreshToken?: string;
            tokenType?: string;
            /** Format: int64 */
            expiresIn?: number;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        LoginRequest: {
            usernameOrEmail: string;
            password: string;
        };
        GoogleAuthRequest: {
            idToken: string;
        };
        ActivityLapRequest: {
            /** Format: double */
            distanceMeters?: number;
            /** Format: int32 */
            durationSeconds?: number;
            /** Format: double */
            averagePaceMinPerKm?: number;
            /** Format: int32 */
            averageHeartRate?: number;
        };
        ActivityRouteRequest: {
            encodedPolyline?: string;
            elevationData?: string;
        };
        CreateActivityRequest: {
            title?: string;
            /** @enum {string} */
            type: "RUN" | "RIDE" | "HIKE" | "WALK" | "SWIM" | "ROW" | "OTHER";
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            completedAt?: string;
            /** Format: int32 */
            durationSeconds?: number;
            /** Format: double */
            distanceMeters?: number;
            /** Format: double */
            elevationGainMeters?: number;
            /** Format: int32 */
            averageHeartRate?: number;
            /** Format: int32 */
            maxHeartRate?: number;
            /** Format: int32 */
            calories?: number;
            notes?: string;
            route?: components["schemas"]["ActivityRouteRequest"];
            laps?: components["schemas"]["ActivityLapRequest"][];
        };
        ActivityDetailResponse: {
            /** Format: uuid */
            id?: string;
            title?: string;
            /** @enum {string} */
            type?: "RUN" | "RIDE" | "HIKE" | "WALK" | "SWIM" | "ROW" | "OTHER";
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            completedAt?: string;
            /** Format: int32 */
            durationSeconds?: number;
            /** Format: double */
            distanceMeters?: number;
            /** Format: double */
            elevationGainMeters?: number;
            /** Format: int32 */
            averageHeartRate?: number;
            /** Format: int32 */
            maxHeartRate?: number;
            /** Format: int32 */
            calories?: number;
            notes?: string;
            route?: components["schemas"]["ActivityRouteResponse"];
            laps?: components["schemas"]["ActivityLapResponse"][];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ActivityLapResponse: {
            /** Format: int32 */
            lapNumber?: number;
            /** Format: double */
            distanceMeters?: number;
            /** Format: int32 */
            durationSeconds?: number;
            /** Format: double */
            averagePaceMinPerKm?: number;
            /** Format: int32 */
            averageHeartRate?: number;
        };
        ActivityRouteResponse: {
            encodedPolyline?: string;
            elevationData?: string;
        };
        UpdateWorkoutRequest: {
            title?: string;
            notes?: string;
            /** Format: date-time */
            completedAt?: string;
            /** Format: int32 */
            rpe?: number;
        };
        UpdateProfileRequest: {
            displayName?: string;
            bio?: string;
            /** Format: date */
            dateOfBirth?: string;
            /** @enum {string} */
            gender?: "MALE" | "FEMALE" | "OTHER" | "PREFER_NOT_TO_SAY";
            /** Format: int32 */
            heightCm?: number;
            /** Format: double */
            weightKg?: number;
        };
        UpdateActivityRequest: {
            title?: string;
            /** @enum {string} */
            type?: "RUN" | "RIDE" | "HIKE" | "WALK" | "SWIM" | "ROW" | "OTHER";
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            completedAt?: string;
            /** Format: int32 */
            durationSeconds?: number;
            /** Format: double */
            distanceMeters?: number;
            /** Format: double */
            elevationGainMeters?: number;
            /** Format: int32 */
            averageHeartRate?: number;
            /** Format: int32 */
            maxHeartRate?: number;
            /** Format: int32 */
            calories?: number;
            notes?: string;
            route?: components["schemas"]["ActivityRouteRequest"];
            laps?: components["schemas"]["ActivityLapRequest"][];
        };
        PageResponseWorkoutResponse: {
            content?: components["schemas"]["WorkoutResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            last?: boolean;
        };
        LastSetResponse: {
            /** Format: uuid */
            exerciseId?: string;
            /** Format: int32 */
            reps?: number;
            /** Format: double */
            weightKg?: number;
            /** Format: int32 */
            durationSeconds?: number;
            /** Format: double */
            distanceMeters?: number;
        };
        UserProfileResponse: {
            /** Format: uuid */
            id?: string;
            username?: string;
            displayName?: string;
            bio?: string;
            profilePictureUrl?: string;
            /** Format: date-time */
            joinedAt?: string;
        };
        UserStatsResponse: {
            /** Format: int64 */
            totalWorkouts?: number;
            /** Format: int64 */
            totalActivities?: number;
            /** Format: double */
            totalDistanceMeters?: number;
            /** Format: double */
            totalVolumeKg?: number;
        };
        ExerciseRecordsResponse: {
            /** Format: uuid */
            exerciseId?: string;
            exerciseName?: string;
            records?: components["schemas"]["PersonalRecordResponse"][];
        };
        PersonalRecordResponse: {
            /** @enum {string} */
            type?: "ONE_REP_MAX" | "MAX_WEIGHT" | "MAX_VOLUME" | "MAX_REPS_AT_WEIGHT";
            /** Format: double */
            value?: number;
            /** Format: date-time */
            achievedAt?: string;
            /** Format: uuid */
            workoutSetId?: string;
            /** Format: double */
            contextWeightKg?: number;
        };
        ProgressionPointResponse: {
            /** Format: date-time */
            date?: string;
            /** Format: double */
            estimatedOneRepMax?: number;
            /** Format: double */
            bestWeightKg?: number;
            /** Format: double */
            volumeKg?: number;
        };
        ChartPoint: {
            /** Format: date */
            date?: string;
            /** Format: double */
            volumeKg?: number;
            /** Format: double */
            distanceKm?: number;
        };
        DashboardResponse: {
            week?: components["schemas"]["WeekSummary"];
            trainingCalendar?: components["schemas"]["DayActivity"][];
            chartData?: components["schemas"]["ChartPoint"][];
            recentPrs?: components["schemas"]["PersonalRecordResponse"][];
        };
        DayActivity: {
            /** Format: date */
            date?: string;
            hasWorkout?: boolean;
            hasActivity?: boolean;
        };
        WeekSummary: {
            /** Format: double */
            volumeKg?: number;
            /** Format: int32 */
            workouts?: number;
            /** Format: double */
            distanceKm?: number;
            /** Format: int32 */
            activeDays?: number;
        };
        ActivityListItemResponse: {
            /** Format: uuid */
            id?: string;
            title?: string;
            /** @enum {string} */
            type?: "RUN" | "RIDE" | "HIKE" | "WALK" | "SWIM" | "ROW" | "OTHER";
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            completedAt?: string;
            /** Format: int32 */
            durationSeconds?: number;
            /** Format: double */
            distanceMeters?: number;
            /** Format: int32 */
            calories?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        PageResponseActivityListItemResponse: {
            content?: components["schemas"]["ActivityListItemResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            last?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RoutineResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoutineRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RoutineResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getById_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ExerciseResponse"];
                };
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateExerciseRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ExerciseResponse"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseWorkoutResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkoutRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkoutResponse"];
                };
            };
        };
    };
    addSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddSetRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkoutSetResponse"];
                };
            };
        };
    };
    uploadAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserSelfResponse"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RoutineResponse"][];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoutineRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RoutineResponse"];
                };
            };
        };
    };
    start: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkoutResponse"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: {
                q?: string;
                muscle?: "CHEST" | "BACK" | "SHOULDERS" | "BICEPS" | "TRICEPS" | "QUADRICEPS" | "HAMSTRINGS" | "GLUTES" | "CALVES" | "CORE" | "FOREARMS" | "FULL_BODY";
                equipment?: "BARBELL" | "DUMBBELL" | "MACHINE" | "CABLE" | "BODYWEIGHT" | "KETTLEBELL" | "RESISTANCE_BAND" | "OTHER";
                movement?: "COMPOUND" | "ISOLATION";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ExerciseResponse"][];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateExerciseRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ExerciseResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    google: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleAuthRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    list_3: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseActivityListItemResponse"];
                };
            };
        };
    };
    create_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateActivityRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ActivityDetailResponse"];
                };
            };
        };
    };
    getById_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkoutResponse"];
                };
            };
        };
    };
    delete_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWorkoutRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkoutResponse"];
                };
            };
        };
    };
    removeSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                setId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                setId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkoutSetRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkoutSetResponse"];
                };
            };
        };
    };
    getSelf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserSelfResponse"];
                };
            };
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserSelfResponse"];
                };
            };
        };
    };
    getById_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ActivityDetailResponse"];
                };
            };
        };
    };
    delete_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateActivityRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ActivityDetailResponse"];
                };
            };
        };
    };
    lastSets: {
        parameters: {
            query: {
                exerciseIds: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LastSetResponse"][];
                };
            };
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserProfileResponse"];
                };
            };
        };
    };
    getStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserStatsResponse"];
                };
            };
        };
    };
    getRecords: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ExerciseRecordsResponse"][];
                };
            };
        };
    };
    records: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PersonalRecordResponse"][];
                };
            };
        };
    };
    progression: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProgressionPointResponse"][];
                };
            };
        };
    };
    history: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkoutSetResponse"][];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DashboardResponse"];
                };
            };
        };
    };
}
